common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: ecom

development:
  <<: *common
  database: ecom_development

test:
  <<: *common
  database: ecom_test

production:
  <<: *common
  database: ecom_production
